services:
  registry:
    container_name: registry
    hostname: registry
    restart: always
    image: docker.io/registry:3
#    labels:
#      - pangolin.proxy-resources.registry.name=Registry
#      - pangolin.proxy-resources.registry.full-domain=registry.pangolin.openstudiolandscapes.cloud-ip.cc
#      - pangolin.proxy-resources.registry.protocol=http
#      - pangolin.proxy-resources.registry.auth.sso-enabled=true
#      - pangolin.proxy-resources.registry.targets[0].method=https
#      - pangolin.proxy-resources.registry.targets[0].hostname=registry
#      - pangolin.proxy-resources.registry.targets[0].port=5000
    depends_on:
      newt:
        condition: service_started
    volumes:
      - ../.volumes/data/registry/data:/var/lib/registry:rw
      - ../.volumes/data/registry/certs:/certs:ro
      - ../.volumes/data/registry/auth:/auth:ro
    env_file:
      - ../.env/registry.env
    ports:
      - "5000:5000"

  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    depends_on:
      registry:
        condition: service_started
    env_file:
      - ../.env/registry.env
    container_name: registry-ui
