
server {
    listen 80;
    listen [::]:80;
    server_name viewvc.memoriaworks.com;

    # ViewVC static assets
    location /viewvc-static/ {
        alias /usr/local/viewvc/templates/docroot/;
    }

    # ViewVC - strip /repo prefix before passing to CGI
    location ~ ^/repo(/.*)?$ {
        gzip off;
        fastcgi_pass unix:/var/run/fcgiwrap.socket;
        fastcgi_param SCRIPT_FILENAME /usr/local/viewvc/bin/cgi/viewvc.cgi;
        fastcgi_param SCRIPT_NAME /repo;
        fastcgi_param PATH_INFO $1;
        fastcgi_param QUERY_STRING $query_string;
        fastcgi_param REMOTE_USER $remote_user;
        fastcgi_param SERVER_NAME $server_name;
        fastcgi_param SERVER_PORT $server_port;
        fastcgi_param SERVER_PROTOCOL $server_protocol;
        fastcgi_param REQUEST_METHOD $request_method;
        fastcgi_param CONTENT_TYPE $content_type;
        fastcgi_param CONTENT_LENGTH $content_length;
        include fastcgi_params;
    }

}
