networks:
  network_openstudiolandscapes_hub:
    name: network_openstudiolandscapes_hub
#    external: false
  network_openstudiolandscapes_hub_traefik:
    name: network_openstudiolandscapes_hub_traefik
#    external: false

include:
#  - path: traefik/docker-compose.traefik.yml
#    project_directory: ./traefik
#  - path: registry/docker-compose.registry.yml
#    project_directory: ./registry
#  - path: pihole/docker-compose.pihole.yml
#    project_directory: ./pihole
  - path: pangolin/docker-compose.pangolin.yml
    project_directory: ./pangolin
#  - path: teleport/docker-compose.teleport.yml
#    project_directory: ./teleport
#  - path: portainer/docker-compose.portainer.yml
#    project_directory: ./portainer
