networks:
  network_openstudiolandscapes_hub:
    name: network_openstudiolandscapes_hub
#    external: false
  network_openstudiolandscapes_hub_traefik:
    name: network_openstudiolandscapes_hub_traefik
#    external: false

include:
  - path: traefik/docker-compose.traefik.yml
    project_directory: ./traefik
#  - path: registry/docker-compose.yml
#    project_directory: ./registry
  - path: pihole/docker-compose.pihole.yml
    project_directory: ./pihole
##  - path: filebrowser/docker-compose.yml
##    project_directory: /home/user/git/repos/server/filebrowser
#  - path: teleport/docker-compose.yml
#    project_directory: /home/michael/git/repos/OpenStudioLandscapes-Infra/teleport
#  - path: portainer/docker-compose.yml
#    project_directory: ./portainer
