services:
  pangolin:
    image: fosrl/pangolin:latest # https://github.com/fosrl/pangolin/releases
    container_name: pangolin
    restart: unless-stopped
    volumes:
      - ../.volumes/config/pangolin/config.yml:/app/config/config.yml
      - ../.volumes/config/pangolin/certificates:/var/certificates:ro
      - ../.volumes/config/pangolin/dynamic:/var/dynamic:ro
    healthcheck:
      test: [
        "CMD",
        "curl",
        "-f",
        "http://localhost:3001/api/v1/"
      ]
      interval: "3s"
      timeout: "3s"
      retries: 15

  gerbil:
    image: fosrl/gerbil:latest # https://github.com/fosrl/gerbil/releases
    container_name: gerbil
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3004
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/
    volumes:
      - ../.volumes/data/pangolin/gerbil/config/:/var/config:rw
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "51820:51820/udp"
      - "21820:21820/udp"
      - "443:443" # Port for traefik because of the network_mode
      - "80:80" # Port for traefik because of the network_mode
      # For Traefik Dashboard (8080) access, create a new Site
      # in Pangolin of type "Local";
      # no need to expose the port here.
      # - https://github.com/orgs/fosrl/discussions/402
      # - https://github.com/fosrl/pangolin/issues/564
      # - "8080:8080"

  traefik:
    image: traefik:v3.4.0
    container_name: traefik
    env_file:
      - ../.env/pangolin.env
    restart: unless-stopped
    network_mode: service:gerbil # Ports appear on the gerbil service
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - ../.volumes/config/pangolin/traefik/dynamic_config.yml:/etc/traefik/dynamic_config.yml:ro # Volume to store the Traefik configuration
      - ../.volumes/config/pangolin/traefik/traefik_config.yml:/etc/traefik/traefik_config.yml:ro # Volume to store the Traefik configuration
      - ../.volumes/data/pangolin/traefik/letsencrypt:/letsencrypt:rw # Volume to store the Let's Encrypt certificates
      # Shared volume for certificates and dynamic config in file mode
      - ../.volumes/config/pangolin/certificates:/var/certificates:ro
      - ../.volumes/config/pangolin/dynamic:/var/dynamic:ro

networks:
  default:
    driver: bridge
    name: pangolin
