services:
  pangolin:
    image: fosrl/pangolin:latest # https://github.com/fosrl/pangolin/releases
    container_name: pangolin
    restart: unless-stopped
    volumes:
      - ../.volumes/pangolin/config:/app/config
      - ../.volumes/pangolin/data:/var/certificates
      - ../.volumes/pangolin/data:/var/dynamic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "3s"
      timeout: "3s"
      retries: 15

  gerbil:
    image: fosrl/gerbil:latest # https://github.com/fosrl/gerbil/releases
    container_name: gerbil
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3004
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/
    volumes:
      - ../.volumes/pangolin/config/:/var/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - 21820:21820/udp
      - 443:443 # Port for traefik because of the network_mode
      - 80:80 # Port for traefik because of the network_mode

  traefik:
    image: traefik:v3.4.0
    container_name: traefik
    ############################
    # USE THIS FOR DNS-CHALLENGE
    env_file:
      - path: ./.env
        required: true
    environment:
      # https://go-acme.github.io/lego/dns/cloudns/index.html
      - CLOUDNS_AUTH_ID=${ENV_CLOUDNS_AUTH_ID}
      - CLOUDNS_AUTH_PASSWORD=${ENV_CLOUDNS_AUTH_PASSWORD}
      - LEGO_DISABLE_CNAME_SUPPORT=true
    ############################
    restart: unless-stopped
    network_mode: service:gerbil # Ports appear on the gerbil service
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - ../.volumes/pangolin/config/traefik:/etc/traefik:ro # Volume to store the Traefik configuration
      - ../.volumes/pangolin/config/letsencrypt:/letsencrypt # Volume to store the Let's Encrypt certificates
      # Shared volume for certificates and dynamic config in file mode
      - ../.volumes/pangolin/data:/var/certificates:ro
      - ../.volumes/pangolin/data:/var/dynamic:ro

networks:
  default:
    driver: bridge
    name: pangolin

#volumes:
#  pangolin-data: