# Guacamole for ARM:
# https://hub.docker.com/search?q=Guacamole&architecture=arm%2Carm64
# https://hub.docker.com/r/flcontainers/guacamole
services:
  guacamole:
    image: flcontainers/guacamole
    container_name: guacamole
#    networks:
#      - pangolin
    env_file:
      - ../.env/guacamole.env
    volumes:
      - ../.volumes/data/guacamole/postgres:/config
      - ../.volumes/data/guacamole/recordings:/var/lib/guacamole/recordings
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - "4822:4822"
