Le_Domain='openstudiolandscapes.cloud-ip.cc'
Le_Alt='teleport.openstudiolandscapes.cloud-ip.cc,*.teleport.openstudiolandscapes.cloud-ip.cc'
Le_Webroot='dns_cloudns'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme-v02.api.letsencrypt.org/directory'
Le_Keylength='ec-256'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/2771984731/444533045721'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/2771984731/444533045721'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/06e3c0a5fb67735ffd8e31626745791b069c'
Le_CertCreateTime='1762173233'
Le_CertCreateTimeStr='2025-11-03T12:33:53Z'
Le_NextRenewTimeStr='2026-01-01T12:33:53Z'
Le_NextRenewTime='1767270833'
