Le_Domain='openstudiolandscapes.cloud-ip.cc'
Le_Alt='teleport.openstudiolandscapes.cloud-ip.cc,*.teleport.openstudiolandscapes.cloud-ip.cc'
Le_Webroot='dns_cloudns'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme-staging-v02.api.letsencrypt.org/directory'
Le_Keylength='ec-256'
Le_OrderFinalize='https://acme-staging-v02.api.letsencrypt.org/acme/finalize/239955653/28469426063'
Le_LinkOrder='https://acme-staging-v02.api.letsencrypt.org/acme/order/239955653/28469426063'
Le_LinkCert='https://acme-staging-v02.api.letsencrypt.org/acme/cert/2c0039e47e64cab7ac5bb95bde0834dea0c5'
Le_CertCreateTime='1762169487'
Le_CertCreateTimeStr='2025-11-03T11:31:27Z'
Le_NextRenewTimeStr='2026-01-01T11:31:27Z'
Le_NextRenewTime='1767267087'
