# https://github.com/ChristianLempa/boilerplates/blob/backup/boilerplates-v1/docker-compose/teleport/config/teleport.yaml

# Teleport Config Reference:
# https://goteleport.com/docs/reference/deployment/config/

version: v3

auth_service:
  enabled: 'yes'
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  cluster_name: "teleport.example.com"  # <-- Set cluster_name

proxy_service:
  acme:
    enabled: false
  enabled: true
  https_keypairs: []
  https_keypairs_reload_interval: 120s
  listen_addr: 0.0.0.0:3023
  public_addr:
  - localhost:443  # <-- Set public_addr
#  - teleport.example.com:443  # <-- Set public_addr
#  - teleport.example.lan:443
#  tunnel_listen_addr: 0.0.0.0:3024
  web_listen_addr: 0.0.0.0:3080

ssh_service:
  enabled: false

teleport:
  ca_pin: ''
  data_dir: /var/lib/teleport
  diag_addr: ''
  join_params:
    method: github
    token_name: ''
  log:
    format:
      output: text
    output: stderr
    severity: INFO
  nodename: teleport.example.com  # <-- Set nodename

app_service:
  apps:
  - description: 'Kitsu Production Tracking'
    insecure_skip_verify: false
    name: kitsu
    public_addr: kitsu.teleport.example.com  # <-- Set public_addr
    rewrite:
      redirect: []
    uri: http://kitsu.example.lan:4545  # <-- Set uri
    use_any_proxy_public_addr: false
  - description: 'OpenStudioLandscapesHub-Dagster'
    insecure_skip_verify: false
    name: openstudiolandscapes-dagster
    public_addr: openstudiolandscapes-dagster.teleport.example.com  # <-- Set public_addr
    rewrite:
      redirect: []
    uri: http://openstudiolandscapes-dagster.example.lan:3000/  # <-- Set uri
    use_any_proxy_public_addr: false
  - description: 'OpenStudioLandscapesHub-Pihole'
    insecure_skip_verify: false
    name: pihole
    public_addr: pihole.teleport.example.com  # <-- Set public_addr
    rewrite:
      redirect: []
    uri: http://pihole.example.lan/admin/  # <-- Set uri
    use_any_proxy_public_addr: false
  - description: 'OpenStudioLandscapesHub-Portainer'
    insecure_skip_verify: true  # For self-signed certificates: https://goteleport.com/docs/enroll-resources/application-access/guides/connecting-apps/#skip-tls-certificate-verification
    name: portainer
    public_addr: portainer.teleport.example.com  # <-- Set public_addr
    rewrite:
      redirect: []
    uri: https://portainer.example.lan/  # <-- Set uri
    use_any_proxy_public_addr: false
  debug_app: false
  enabled: true
  mcp_demo_server: false
