app:
  dashboard_url: "https://pangolin.faranna.de"
  # https://docs.pangolin.net/self-host/telemetry#configuration
  telemetry:
    anonymous_usage: false  # Set to false to disable

domains:
  domain1:
    base_domain: "pangolin.faranna.de"
    cert_resolver: "letsencrypt"

server:
  secret: "my-strong-secret"

gerbil:
  base_endpoint: "pangolin.faranna.de"

flags:
  require_email_verification: false
  disable_signup_without_invite: true
  disable_user_create_org: true
