services:
  service_openstudiolandscapes_hub_portainer:
    container_name: openstudiolandscapes-hub-portainer
    image: docker.io/portainer/portainer-ce:lts
    hostname: openstudiolandscapes-hub-portainer
#    depends_on:
#      service_openstudiolandscapes_hub_traefik:
#        condition: "service_started"
#        required: true
    env_file:
      - .env
#    environment:
#      - TRUSTED_ORIGINS=portainer.teleport.openstudiolandscapes.cloud-ip.cc
    restart: "unless-stopped"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - /etc/localtime:/etc/localtime:ro
      - ../.volumes/portainer/portainer_data:/data:rw
    networks:
      - network_openstudiolandscapes_hub_traefik
    ports:
      - "9443:9443"
#      - "8000:8000"  # Remove if you do not intend to use Edge Agents
