services:
  portainer:
    container_name: portainer
    image: docker.io/portainer/portainer-ce:lts
    hostname: portainer
    command:
      # This initializes a vanilla Portainer
      # instance with user admin and
      # password DEFAULT_ADMIN_PASSWORD
      - --admin-password
      - ${DEFAULT_ADMIN_PASSWORD}
    depends_on:
      newt:
        condition: service_started
      # pihole-unbound:
      #   condition: service_healthy
#    labels:
#      - pangolin.proxy-resources.portainer.name=Portainer
#      - pangolin.proxy-resources.portainer.full-domain=portainer.pangolin.openstudiolandscapes.cloud-ip.cc
#      - pangolin.proxy-resources.portainer.protocol=http
#      - pangolin.proxy-resources.portainer.auth.sso-enabled=true
#      - pangolin.proxy-resources.portainer.targets[0].method=https
#      - pangolin.proxy-resources.portainer.targets[0].hostname=portainer
#      - pangolin.proxy-resources.portainer.targets[0].port=9443
#    depends_on:
#      newt:
#        condition: service_started
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../.volumes/portainer/data:/data:rw
