services:
  portainer:
    container_name: portainer
    image: docker.io/portainer/portainer-ce:lts
    hostname: portainer.farm.evil
    domainname: farm.evil
    depends_on:
      caddy:
        condition: service_started
    env_file:
      - .env
    environment:
      - TRUSTED_ORIGINS=portainer.teleport.openstudiolandscapes.cloud-ip.cc
    restart: "no"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data
#      -
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
      - ./volumes/portainer_data:/data:rw
    networks:
      - caddy
#    ports:
#      - 9443:9443
##      - 8000:8000  # Remove if you do not intend to use Edge Agents

#volumes:
#  portainer_data:
#    name: portainer_data

networks:
  default:
    name: portainer_network