services:
  portainer:
    container_name: portainer
    image: docker.io/portainer/portainer-ce:lts
    hostname: portainer
#    labels:
#      - pangolin.proxy-resources.portainer.name=Portainer
#      - pangolin.proxy-resources.portainer.full-domain=portainer.pangolin.openstudiolandscapes.cloud-ip.cc
#      - pangolin.proxy-resources.portainer.protocol=http
#      - pangolin.proxy-resources.portainer.auth.sso-enabled=true
#      - pangolin.proxy-resources.portainer.targets[0].method=https
#      - pangolin.proxy-resources.portainer.targets[0].hostname=portainer
#      - pangolin.proxy-resources.portainer.targets[0].port=9443
    depends_on:
      newt:
        condition: service_started
    environment:
      - TRUSTED_ORIGINS=${TRUSTED_ORIGINS}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../.volumes/data/portainer:/data:rw
