api:
  insecure: true
  dashboard: true

providers:
  http:
    endpoint: "http://pangolin:3001/api/v1/traefik-config"
    pollInterval: "5s"
  file:
    filename: "/etc/traefik/dynamic_config.yml"

experimental:
  plugins:
    badger:
      moduleName: "github.com/fosrl/badger"
      version: "v1.2.0"

log:
  level: "INFO"
  format: "common"

#certificatesResolvers:
#  letsencrypt:
#    acme:
#      httpChallenge:
#        entryPoint: web
#      email: <YOUR_EMAIL> # REPLACE WITH YOUR EMAIL
#      storage: "/letsencrypt/acme.json"
#      caServer: "https://acme-v02.api.letsencrypt.org/directory"

# -- Configure your CertificateResolver here...
certificatesResolvers:
# Uncomment the resolvers that apply to your DNS Provider
#  # https://doc.traefik.io/traefik/reference/install-configuration/tls/certificate-resolvers/acme/
#  # Cloudflare
#  # https://go-acme.github.io/lego/dns/cloudflare/index.html
  cloudflare_production:
    acme:
      email: <YOUR_EMAIL>  # <-- Change this to your email
      storage: /letsencrypt/acme.cloudflare_production.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare  # <-- (Optional) Change this to your DNS provider
        resolvers:
          - "1.1.1.1:53"

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: "30m"
    http:
      tls:
        certResolver: "cloudflare_production"  # <-- i.e. "cloudflare_production"

serversTransport:
  insecureSkipVerify: true

ping:
    entryPoint: "web"
