---

# https://github.com/ChristianLempa/boilerplates/blob/backup/boilerplates-v1/docker-compose/teleport/compose.yaml

services:
  openstudiolandscapeshub-teleport:
    container_name: openstudiolandscapeshub-teleport
#    domainname: openstudiolandscapes.lan
#    hostname: teleport.farm.evil
    entrypoint:
    - /usr/bin/dumb-init
    - /usr/local/bin/teleport
    - start
    - -c
    - /etc/teleport/teleport.yaml
    image: public.ecr.aws/gravitational/teleport-distroless-debug:18
    networks:
#      - teleport
      - openstudiolandscapes_hub
      - openstudiolandscapes_hub_traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.teleport.loadbalancer.server.port=3080"
      - "traefik.http.services.teleport.loadbalancer.server.scheme=https"
      # HostRegexp:
      # https://doc.traefik.io/traefik/master/reference/routing-configuration/http/routing/rules-and-priority/#rulesyntax
      #
      # Rule HTTP
      - "traefik.http.routers.teleport-http.entrypoints=web"
      - "traefik.http.routers.teleport-http.rule=HostRegexp(`^(?i)(?:[[:alnum:]]+(?:-+[[:alnum:]]+)*\\.)?teleport.openstudiolandscapes.cloud-ip.cc(?::\\d+)?$`)"
      # Rule HTTPS
      - "traefik.http.routers.teleport-https.entrypoints=websecure"
      - "traefik.http.routers.teleport-https.rule=HostRegexp(`^(?i)(?:[[:alnum:]]+(?:-+[[:alnum:]]+)*\\.)?teleport.openstudiolandscapes.cloud-ip.cc(?::\\d+)?$`)"
      - "traefik.http.routers.teleport-https.tls=true"
#      - "traefik.http.routers.teleport-https.tls.certresolver=your-certresolver"  # see traefik/volumes/config/traefik.yaml:certificatesResolvers
#      - "traefik.http.routers.teleport-https.tls.certresolver=cloudns_staging"
      - "traefik.http.routers.teleport-https.tls.certresolver=cloudns_production"
#      - "traefik.http.routers.teleport-https.tls.domains[0].main=your-server-url"
      - "traefik.http.routers.teleport-https.tls.domains[0].main=teleport.openstudiolandscapes.cloud-ip.cc"
#      - "traefik.http.routers.teleport-https.tls.domains[0].sans=*.your-server-url"
      - "traefik.http.routers.teleport-https.tls.domains[0].sans=*.teleport.openstudiolandscapes.cloud-ip.cc"
      # Transmission
#      - "traefik.http.routers.transmission.entrypoints=web"
#      - "traefik.http.routers.transmission.rule=Host(`transmission.openstudiolandscapes.lan`)"
    volumes:
    - ./volumes/config:/etc/teleport:rw
    - ./volumes/data:/var/lib/teleport:rw
