---

# https://github.com/ChristianLempa/boilerplates/blob/backup/boilerplates-v1/docker-compose/teleport/compose.yaml

services:
  openstudiolandscapes_hub_teleport:
    container_name: openstudiolandscapes-hub-teleport
    hostname: openstudiolandscapes-hub-teleport
#    domainname: openstudiolandscapes.lan
#    hostname: teleport.farm.evil
    entrypoint:
    - /usr/bin/dumb-init
    - /usr/local/bin/teleport
    - start
    - -c
    - /etc/teleport/teleport.yaml
    image: public.ecr.aws/gravitational/teleport-distroless-debug:18
    networks:
      - network_openstudiolandscapes_hub
#      - network_openstudiolandscapes_hub_traefik
#    depends_on:
#      service_openstudiolandscapes_hub_traefik:
#        condition: "service_started"
#        required: true
    restart: unless-stopped
    ports:
      - "3080:3080"
#    labels:
#      # <YOUR_WAN_DOMAIN>=teleport.example.com
#      - "traefik.enable=true"
#      - "traefik.http.services.teleport.loadbalancer.server.port=3080"
#      - "traefik.http.services.teleport.loadbalancer.server.scheme=https"
#      # HostRegexp:
#      # https://doc.traefik.io/traefik/master/reference/routing-configuration/http/routing/rules-and-priority/#rulesyntax
#      #
#      # Rule HTTP
#      - "traefik.http.routers.teleport-http.entrypoints=web"
#      - "traefik.http.routers.teleport-http.rule=HostRegexp(`^(?i)(?:[[:alnum:]]+(?:-+[[:alnum:]]+)*\\.)?<YOUR_WAN_DOMAIN>(?::\\d+)?$`)"
#      # Rule HTTPS
#      - "traefik.http.routers.teleport-https.entrypoints=websecure"
#      - "traefik.http.routers.teleport-https.rule=HostRegexp(`^(?i)(?:[[:alnum:]]+(?:-+[[:alnum:]]+)*\\.)?<YOUR_WAN_DOMAIN>(?::\\d+)?$`)"
#      - "traefik.http.routers.teleport-https.tls=true"
##      - "traefik.http.routers.teleport-https.tls.certresolver=your-certresolver"  # see traefik/volumes/config/traefik.yaml:certificatesResolvers
##      - "traefik.http.routers.teleport-https.tls.certresolver=cloudns_staging"
#      - "traefik.http.routers.teleport-https.tls.certresolver=cloudns_production"
##      - "traefik.http.routers.teleport-https.tls.domains[0].main=your-server-url"
#      - "traefik.http.routers.teleport-https.tls.domains[0].main=<YOUR_WAN_DOMAIN>"
##      - "traefik.http.routers.teleport-https.tls.domains[0].sans=*.your-server-url"
#      - "traefik.http.routers.teleport-https.tls.domains[0].sans=*.<YOUR_WAN_DOMAIN>"
    volumes:
    - ../.volumes/teleport/config:/etc/teleport:rw
    - ../.volumes/teleport/data:/var/lib/teleport:rw
